version: '3.7'
services:
  frontend:
    image: judithed/sfia2-frontend:${app_version}
    build: .
    depends_on:
      - backend
  backend:
    image: judithed/sfia2-backend:${app_version}
    build: .
    environment:
      - SECRET_KEY=${DB_PASSWORD}
      - DATABASE_URI=${DATABASE_URI}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TEST_DATABASE_URI=${TEST_DATABASE_URI}
      - DB_PASSWORD=${DB_PASSWORD}
  nginx:
    image: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
