version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
  backend:
    image: backend
    build: ./backend
    depends_on:
      - mysql
  mysql:
    image: flask-db
    build: ./db
    environment:
      - SECRET_KEY=${DB_PASSWORD}
      - MYSQL_DATABASE=flask-db
      - DATABASE_URI=${DATABASE_URI}
  nginx:
    image: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend


